-- PostgreSQL role, matching the remote migration actor: non-superuser, no
-- membership of the managed superuser supabase_admin. Never fake this grant.
select pg_temp.replay_assert(not (select rolsuper from pg_roles where rolname='postgres'),'migration tested as non-superuser postgres');
select pg_temp.replay_assert(not pg_has_role('postgres','supabase_admin','MEMBER'),'managed creator defaults are inaccessible to migration role');
select pg_temp.replay_assert(not exists(
 select 1 from pg_temp.hardening_fk_snapshot b left join pg_constraint c on c.oid=b.oid
 where c.oid is null or pg_get_constraintdef(c.oid)<>b.definition or c.convalidated<>b.convalidated),'historical FK definitions/validation untouched');
select pg_temp.replay_assert((select count(*) from pg_temp.hardening_fk_snapshot)=(select count(*) from pg_constraint c join pg_class t on t.oid=c.conrelid join pg_namespace n on n.oid=t.relnamespace where n.nspname='public' and c.contype='f'),'no FK added or removed by hardening');
select pg_temp.replay_assert(not exists(
 select 1 from pg_temp.hardening_function_snapshot b left join pg_proc p on p.oid=b.oid
 where p.oid is null or pg_get_functiondef(p.oid)<>b.definition),'all existing function bodies/search_paths unchanged');

set local role postgres;
create table public.hardening_future_table(id bigint generated by default as identity primary key,label text);
alter table public.hardening_future_table enable row level security;
create function public.hardening_future_rpc() returns integer language sql security invoker set search_path=pg_catalog as $$ select 1 $$;
reset role;
do $$ declare name text; role_name text; permission text; begin
 foreach role_name in array array['anon','authenticated'] loop
  foreach permission in array array['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER','MAINTAIN'] loop
   perform pg_temp.replay_assert(not has_table_privilege(role_name,'public.hardening_future_table',permission),'future table browser permission denied');
  end loop;
  foreach permission in array array['USAGE','SELECT','UPDATE'] loop
   perform pg_temp.replay_assert(not has_sequence_privilege(role_name,'public.hardening_future_table_id_seq',permission),'future sequence browser access denied');
  end loop;
  perform pg_temp.replay_assert(not has_function_privilege(role_name,'public.hardening_future_rpc()','EXECUTE'),'future function does not inherit PUBLIC EXECUTE');
 end loop;
 foreach permission in array array['SELECT','INSERT','UPDATE','DELETE'] loop
  perform pg_temp.replay_assert(has_table_privilege('service_role','public.hardening_future_table',permission),'future server CRUD permission');
 end loop;
 foreach permission in array array['USAGE','SELECT','UPDATE'] loop
  perform pg_temp.replay_assert(has_sequence_privilege('service_role','public.hardening_future_table_id_seq',permission),'server identity sequence permission');
 end loop;
 perform pg_temp.replay_assert(not has_table_privilege('service_role','public.hardening_future_table','TRUNCATE'),'future backend cannot TRUNCATE');
 perform pg_temp.replay_assert(has_function_privilege('service_role','public.hardening_future_rpc()','EXECUTE'),'future server RPC permission');
end $$;
set local role service_role;
insert into public.hardening_future_table(label) values('Synthetic identity row');
update public.hardening_future_table set label='Synthetic updated row';
select pg_temp.replay_assert((select count(*)=1 from public.hardening_future_table where label='Synthetic updated row'),'future backend insert/read/update with identity works');
delete from public.hardening_future_table;
select pg_temp.replay_assert(not exists(select 1 from public.hardening_future_table),'future backend DELETE works');
select pg_temp.replay_assert(public.hardening_future_rpc()=1,'future backend EXECUTE works');
reset role;
select pg_temp.replay_failure('set local role anon; select public.hardening_future_rpc()','42501','future anon EXECUTE denied');
select pg_temp.replay_failure('set local role authenticated; select public.hardening_future_rpc()','42501','future authenticated EXECUTE denied');
select pg_temp.replay_failure('set local role service_role; truncate public.hardening_future_table','42501','future backend TRUNCATE denied');

-- PostgreSQL's global function-default exception necessarily affects all schemas
-- of this creator. Existing objects outside public are not altered.
set local role postgres;
create schema hardening_future_private;
create function hardening_future_private.probe() returns integer language sql set search_path=pg_catalog as $$ select 1 $$;
reset role;
select pg_temp.replay_assert(not has_function_privilege('anon','hardening_future_private.probe()','EXECUTE'),'future non-public function PUBLIC EXECUTE removed too');

-- Document the reserved-creator exception by verifying, not hiding, its defaults.
select pg_temp.replay_assert((select count(*)=3 from pg_default_acl d join pg_namespace n on n.oid=d.defaclnamespace where pg_get_userbyid(d.defaclrole)='supabase_admin' and n.nspname='public'),'three managed public defaults remain');
select pg_temp.replay_assert(not exists(
 select 1 from pg_temp.managed_default_snapshot b left join pg_default_acl d on d.oid=b.oid where d.oid is null or d.defaclacl is distinct from b.acl),'managed defaults exactly preserved');
set local role supabase_admin;
create table public.hardening_managed_creator_probe(id integer);
alter table public.hardening_managed_creator_probe enable row level security;
create function public.hardening_managed_function_probe() returns integer language sql set search_path=pg_catalog as $$ select 1 $$;
reset role;
select pg_temp.replay_assert(has_table_privilege('anon','public.hardening_managed_creator_probe','TRUNCATE'),'managed future creator still has unsafe table defaults: documented exception');
select pg_temp.replay_assert(has_function_privilege('authenticated','public.hardening_managed_function_probe()','EXECUTE'),'managed future function still has unsafe defaults: documented exception');

-- Probe objects are test-only and never remain part of the application schema.
drop table public.hardening_future_table,public.hardening_managed_creator_probe;
drop function public.hardening_future_rpc(),public.hardening_managed_function_probe(),hardening_future_private.probe();
drop schema hardening_future_private;
