export type Source="search_console"|"business_profile"|"google_ads"|"history"|"seasonality"|"editorial_rules";
export type Evidence={id:string;source:Source;description:string;measured_at:string|null;metrics:Record<string,number>};
export type Opportunity={id:string;service:string;subject:string;sources:Evidence[];constraints:string[];dimensions:{seo_potential:number;business_relevance:number;seasonality:number;local_relevance:number;freshness:number;history_penalty:number;media_match:number;factual_confidence:number};score:number;reasons:string[]};
export type OpportunityContext={services:string[];date:string;zone:string|null;recentSubjects:string[];rules:string;clientId:string;projectId:string};
export interface OpportunityProvider{source:Source;collect(context:OpportunityContext):Promise<Opportunity[]>;}
// Digital terms must be whole words: "visite" or "parasites" never become digital.
const digitalService=/(?:^|[^\p{L}])(?:sites?|web|seo|référencement|referencement|ads|automatisations?|ia|digitale?s?|numériques?|numeriques?)(?=$|[^\p{L}])/u;
export function category(service:string):"roof"|"pests"|"paint"|"facade"|"digital"|"other"{const s=service.toLocaleLowerCase('fr');return /toit|couvert|infiltrat/.test(s)?"roof":/nuisibl|guêp|fourmi|insect/.test(s)?"pests":/peint/.test(s)?"paint":/façade|facade|humidité/.test(s)?"facade":digitalService.test(s)?"digital":"other";}
export function candidate(service:string,source:Source,description:string,dimensions:Partial<Opportunity['dimensions']>={}):Opportunity{return {id:`${source}:${service}`,service,subject:`${service} : les points à vérifier`,sources:[{id:`${source}:${service}`,source,description,measured_at:null,metrics:{}}],constraints:['Prestation confirmée par l’admin ; aucun résultat client déduit.'],dimensions:{seo_potential:0,business_relevance:0.7,seasonality:0,local_relevance:0,freshness:0.5,history_penalty:0,media_match:0,factual_confidence:1,...dimensions},score:0,reasons:[]};}
