import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {test} from 'node:test';
import vm from 'node:vm';
import ts from 'typescript';
import * as jsx from 'react/jsx-runtime';
import {renderToStaticMarkup} from 'react-dom/server';
function load(path,mocks){const exports={};const code=ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;vm.runInNewContext(code,{exports,require:name=>name==='react/jsx-runtime'?jsx:mocks[name]??(()=>{throw Error('Unexpected import '+name)})()});return exports;}
const project='30000000-0000-4000-8000-000000000001',publication='40000000-0000-4000-8000-000000000001';
function actionSetup(deny=false){const calls=[];const actions=load('app/(cockpit)/publications/agent-actions.ts',{'next/cache':{revalidatePath:path=>calls.push(['revalidate',path])},'@/lib/require-admin':{requireAdmin:async()=>{if(deny)throw Error('denied');return {userId:'user_local'};}},'@/lib/publications/agent-service':{configurePublicationsAgent:async()=>({message:'Configured'}),preparePublication:async(...args)=>{calls.push(['prepare',...args]);return {message:'Prepared'};}},'@/lib/publications/validation':{isPublicationUuid:s=>typeof s==='string'&&/^[a-f0-9-]{36}$/.test(s)}});return {actions,calls};}
const form=()=>{const f=new FormData();f.set('project_id',project);f.set('publication_id',publication);return f;};
test('Server Action demands explicit authorization for one exact placeholder',async()=>{const r=actionSetup(),f=form();assert.match((await r.actions.prepareAgentAction({},f)).message,/Autorisez/);assert.equal(r.calls.length,0);f.set('authorize_ai','on');assert.equal((await r.actions.prepareAgentAction({},f)).message,'Prepared');assert.equal(r.calls[0][1],project);assert.equal(r.calls[0][2],publication);assert.equal(r.calls[0][3].allowRealAI,true);assert.ok(r.calls.some(c=>c[0]==='revalidate'&&c[1]==='/publications/review'));});
test('Server Action rejects duplicate checkbox values and invalid publication IDs',async()=>{for(const mutate of [f=>{f.append('authorize_ai','on');},f=>f.set('publication_id','bad')]){const r=actionSetup(),f=form();f.set('authorize_ai','on');mutate(f);assert.match((await r.actions.prepareAgentAction({},f)).message,/Autorisez/);assert.equal(r.calls.length,0);}});
test('unauthorized Server Actions do not reach preparation/configuration',async()=>{const r=actionSetup(true);await assert.rejects(()=>r.actions.prepareAgentAction({},form()),/denied/);await assert.rejects(()=>r.actions.configureAgentAction({},form()),/denied/);assert.equal(r.calls.length,0);});
test('project form is limited to one placeholder and requires an unchecked authorization checkbox',()=>{const forms=load('components/publications/agent-forms.tsx',{'react':{useActionState:()=>[{},()=>{},false]},'@/app/(cockpit)/publications/agent-actions':{configureAgentAction:()=>{},prepareAgentAction:()=>{}}});const html=renderToStaticMarkup(jsx.jsx(forms.AgentPrepareForm,{projectId:project,placeholders:[{id:publication,date:'2026-11-02'}]}));assert.match(html,/Préparer les publications/);assert.match(html,/name="publication_id"/);assert.match(html,/name="authorize_ai"/);assert.match(html,/required/);assert.doesNotMatch(html,/checked|multiple/);const regen=renderToStaticMarkup(jsx.jsx(forms.AgentPrepareForm,{projectId:project,publicationId:publication,regenerate:true}));assert.match(regen,/Régénérer/);});
test('configuration reload reflects both activation and confirmed media rights',()=>{const forms=load('components/publications/agent-forms.tsx',{'react':{useActionState:()=>[{},()=>{},false]},'@/app/(cockpit)/publications/agent-actions':{configureAgentAction:()=>{},prepareAgentAction:()=>{}}});const html=renderToStaticMarkup(jsx.jsx(forms.AgentConfigurationForm,{projectId:project,config:{enabled:true,rights_confirmed:true,drive_folder_id:'folder00000001',verified_services:['Couverture'],editorial_rules:'Objectif'}}));assert.equal((html.match(/checked=""/g)??[]).length,2);assert.match(html,/Couverture/);assert.match(html,/folder00000001/);});
function reviewSetup(rows=[],deny=false){const calls=[];const page=load('app/(cockpit)/publications/review/page.tsx',{'next/link':{default:({href,children})=>jsx.jsx('a',{href,children})},'@/lib/require-admin':{requireAdmin:async()=>{calls.push('admin');if(deny)throw Error('denied');}},'@/lib/publications/data':{listPublications:async()=>{calls.push('list');return rows;}},'@/lib/publications/review-cards':{buildReviewCards:async(list,options)=>{calls.push(['cards',options.debug]);return list.map(p=>({publicationId:p.id,status:p.status,subject:p.subject,clientName:p.client.name,projectName:p.project.name}));}},'@/lib/projects/workspace-view':{isDebugView:s=>s.debug==='1'},'@/components/publications/review-queue':{ReviewQueue:({cards,showContext})=>jsx.jsx('section',{'data-context':String(showContext),children:cards.length?cards.map(c=>jsx.jsx('p',{children:`${c.clientName} · ${c.projectName} · ${c.subject}`},c.publicationId)):'Aucune publication en attente'})},'@/components/ui/primitives':{PageHeading:()=>null}});return {page,calls};}
const reviewProps=(search={})=>({searchParams:Promise.resolve(search)});
test('review route renders a clean empty state without creating content',async()=>{assert.match(renderToStaticMarkup(await reviewSetup().page.default(reviewProps())),/Aucune publication en attente/);});
test('global review route shows client and project context through the shared review queue, without scores',async()=>{const r=reviewSetup([{id:publication,status:'pending_review',current_revision_id:'revision',subject:'Sujet',client:{name:'Client local'},project:{name:'Projet social'},target_date:'2026-11-02'}]);const html=renderToStaticMarkup(await r.page.default(reviewProps()));for(const s of ['Client local','Projet social','Sujet','data-context="true"'])assert.ok(html.includes(s),s);assert.ok(!html.includes('/100'));assert.deepEqual(r.calls.find(c=>Array.isArray(c)),['cards',false]);assert.deepEqual((await (async()=>{const d=reviewSetup([]);await d.page.default(reviewProps({debug:'1'}));return d.calls.find(c=>Array.isArray(c));})()),['cards',true]);});
test('review route denies a non-admin before reading data',async()=>{const r=reviewSetup([],true);await assert.rejects(()=>r.page.default(reviewProps()),/denied/);assert.deepEqual(r.calls,['admin']);});
