import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {test} from 'node:test';
import vm from 'node:vm';
import ts from 'typescript';
import {createRequire} from 'node:module';
import {resolve,dirname} from 'node:path';
import sharp from 'sharp';
const native=createRequire(import.meta.url),root=resolve(new URL('..',import.meta.url).pathname.replace(/^\/([A-Z]:)/,'$1'));
function load(file,mocks={},globals={}){const cache=new Map();function read(path){path=resolve(root,path);if(cache.has(path))return cache.get(path);const exports={};cache.set(path,exports);vm.runInNewContext(ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,{exports,Buffer,Uint8Array,URL,AbortSignal,process:{env:{}},...globals,require:name=>{if(name==='server-only')return {};if(name in mocks)return mocks[name];if(name.startsWith('.'))return read(resolve(dirname(path),name)+'.ts');if(name.startsWith('@/'))return read(name.slice(2)+'.ts');return native(name);}});return exports;}return read(file);}
const {candidate}=load('lib/publications/opportunities/types.ts');
const {scoreOpportunity}=load('lib/publications/opportunities/scoring.ts');
const {collectOpportunities}=load('lib/publications/opportunities/service.ts');
const {selectSubjectPhoto}=load('lib/publications/media/matching.ts');
const {validateGeneratedContent}=load('lib/publications/ai/schemas.ts');
const {adaptImage,visionPreview}=load('lib/publications/media/transform.ts');
const client='10000000-0000-4000-8000-000000000001',project='30000000-0000-4000-8000-000000000001',publication='40000000-0000-4000-8000-000000000001';
const context={clientId:client,projectId:project,services:['Couverture','Peinture extérieure'],date:'2026-10-12',zone:null,recentSubjects:[],rules:''};
const photo=(scene='roof')=>({id:'photo',client_id:client,project_id:project,drive_file_id:'drivefile00001',name:'Une photo',mime_type:'image/png',modified_at:'2026-10-01T00:00:00Z',width:800,height:400,size:1200,used:false,analysis:{scene,confidence:.95,usable:true,description:'Surface visible'}});
test('deterministic opportunity providers use confirmed services, seasons and transparent scores',async()=>{const autumn=await collectOpportunities(context),spring=await collectOpportunities({...context,date:'2026-05-12'});assert.ok(autumn.length>=4);assert.equal(autumn[0].service,'Couverture');assert.equal(spring[0].service,'Peinture extérieure');for(const o of autumn){assert.ok(o.score>=0&&o.score<=100);assert.ok(o.reasons.length);assert.ok(context.services.includes(o.service));assert.ok(o.sources.length);}});
test('history penalizes recently used subjects',async()=>{const opportunities=await collectOpportunities({...context,recentSubjects:['Couverture : les points à vérifier']});assert.ok(opportunities.some(o=>o.dimensions.history_penalty===1));});
test('search snapshots filter unconfirmed services and retain measured SEO evidence',async()=>{const {searchConsoleProvider}=load('lib/publications/opportunities/search-console.ts');const row={query:'couverture',service:'Couverture',impressions:1000,clicks:5,position:8,previousImpressions:500,measuredAt:'2026-10-01',local:true};const values=await searchConsoleProvider([row,{...row,service:'Service inventé'},{...row,position:30}]).collect(context);assert.equal(values.length,1);assert.equal(values[0].sources[0].metrics.growth,1);assert.equal(values[0].dimensions.seo_potential,.9);});
test('Ads signals cannot manufacture SEO potential',async()=>{const {googleAdsProvider,applyBusinessSignals}=load('lib/publications/opportunities/google-ads.ts');assert.equal((await googleAdsProvider.collect(context)).length,0);const p=applyBusinessSignals([candidate('Couverture','history','')],[{service:'Couverture',leads:12,measuredAt:'2026-10-01'}]);assert.equal(p[0].dimensions.business_relevance,.95);assert.equal(p[0].dimensions.seo_potential,0);});
test('invalid score dimensions fail closed',()=>assert.throws(()=>scoreOpportunity(candidate('Couverture','history','',{media_match:NaN}))));
test('photo-first chooses a compatible second opportunity instead of forcing the first',()=>{const roof=scoreOpportunity(candidate('Couverture','seasonality','',{seo_potential:1})),paint=scoreOpportunity(candidate('Peinture extérieure','history',''));const pair=selectSubjectPhoto([roof,paint],[photo('paint')],client,project);assert.equal(pair.opportunity.service,'Peinture extérieure');assert.ok(pair.opportunity.dimensions.media_match>0);});
for(const [name,p] of [['used',{...photo(),used:true}],['incompatible',photo('pests')],['uncertain',{...photo(),analysis:{...photo().analysis,confidence:.5}}],['unusable',{...photo(),analysis:{...photo().analysis,usable:false}}],['unknown',photo('other')]])test(`photo ${name} is never selected`,()=>assert.equal(selectSubjectPhoto([candidate('Couverture','history','')],[p],client,project),null));
test('cross-client/project photos are rejected before matching',()=>{for(const p of [{...photo(),client_id:'foreign'},{...photo(),project_id:'foreign'}])assert.throws(()=>selectSubjectPhoto([candidate('Couverture','history','')],[p],client,project));});
function generation(){const opportunity=candidate('Couverture','seasonality','');return {...context,client_name:'Client local',services:context.services,zone:null,website:null,rules:'',subject:opportunity.subject,opportunity,photo:photo(),platforms:['facebook','instagram'],approved_sentences:['Chaque situation mérite une analyse adaptée.','Contactez-nous pour parler de votre besoin.'],rejection:null,previous_texts:[]};}
function output(c){const text=c.approved_sentences.join('\n');return {internal_title:c.subject,subject:c.subject,source_content:text,selected_opportunity:c.opportunity.id,selected_asset_id:c.photo.id,facebook:{text,title:null,cta:null},instagram:{text,title:null,cta:null},google_business_profile:null,factual_basis:c.approved_sentences,generation_summary:'Sujet et photo compatibles ; validation humaine requise.'};}
test('structured output accepts supported facts and channels only',()=>{const c=generation();assert.equal(validateGeneratedContent(output(c),c).selected_asset_id,'photo');});
for(const text of ['Prix : 99 €','Promotion : -20 %','20 années d’expérience','Certifié RGE','Chantier livré à Perpignan','Résultat garanti sous 24 heures','Avis client : parfait','500 clients satisfaits','Réfection complète réalisée'])test(`unsupported claim rejected: ${text}`,()=>{const c=generation(),g=output(c);g.facebook.text=text;assert.throws(()=>validateGeneratedContent(g,c));});
test('output rejects other media, unknown keys, absent factual basis and extra platforms',()=>{const c=generation();for(const patch of [{selected_asset_id:'foreign'},{selected_opportunity:'foreign'},{secret:'bad'},{factual_basis:[]},{google_business_profile:{text:c.approved_sentences[0],title:null,cta:null}}])assert.throws(()=>validateGeneratedContent({...output(c),...patch},c));});
test('actual Sharp derivatives preserve the original aspect ratio and create compatible sizes',async()=>{const bytes=await sharp({create:{width:800,height:400,channels:3,background:'#ff0000'}}).png().toBuffer();for(const platform of ['facebook','instagram','google_business_profile']){const image=await adaptImage(bytes,platform),metadata=await sharp(image.bytes).metadata();assert.equal(metadata.width,platform==='google_business_profile'?1200:1080);assert.equal(metadata.height,platform==='google_business_profile'?900:1080);assert.equal(metadata.format,'jpeg');const {data,info}=await sharp(image.bytes).raw().toBuffer({resolveWithObject:true});assert.ok(data[0]>240&&data[1]>240&&data[2]>240,'white bars retain entire image');const i=(Math.floor(info.height/2)*info.width+Math.floor(info.width/2))*info.channels;assert.ok(data[i]>240&&data[i+1]<20,'red subject retained');}assert.equal((await sharp(bytes).metadata()).height,400);assert.ok((await visionPreview(bytes)).length>0);});
test('invalid/non-photographic media is rejected before vision',async()=>{await assert.rejects(()=>visionPreview(Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"/>')));await assert.rejects(()=>adaptImage(Buffer.from('invalid'),'facebook'));});

async function runtime({reused=false,finishError=false,foreign=false,none=false,rejected=false,deny=false}={}){
 const calls=[],uploads=[],opportunity=candidate('Couverture','seasonality',''),bytes=await sharp({create:{width:800,height:400,channels:3,background:'red'}}).png().toBuffer();let status='processing';
 const ctx={config:{drive_folder_id:'folder00000001',verified_services:['Couverture']},client:{id:client,name:'Local',activity:'Artisan',notes:null,geographic_area:null,website:null},project:{name:'Projet local'},cadence:null,history:[],historyVariants:[],historyReviews:[],mediaUses:[],rules:'',workspace:{publication:{current_revision_id:rejected?'old':null},reviews:rejected?[{revision_id:'old',decision:'rejected',reason:'Changer le sujet'}]:[],variants:[]},opportunities:[opportunity],platforms:['facebook','instagram']};
 const db={rpc:async(name,args)=>{calls.push([name,args]);if(name==='publication_ai_begin')return {data:{run_id:'run',reused,status:reused?'completed':'processing'}};if(name==='publication_ai_catalog')return {data:none?[]:[{id:'media',drive_file_id:'drivefile00001',used:false}]};if(name==='publication_ai_finish'){if(finishError)return {error:{message:'provider secret must not leak'}};status='completed';}if(name==='publication_ai_fail')status='failed';return {data:null};},from:()=>{const q={select:()=>q,eq:()=>q,single:async()=>({data:{status}}),maybeSingle:async()=>({data:{status}})};return q;},storage:{from:bucket=>({upload:async(path,b)=>{uploads.push({bucket,path,bytes:b});return {};},remove:async(paths)=>{calls.push(['remove',paths]);return {};}})}};
 const guard={requireAdmin:async()=>{if(deny)throw Error('denied');return {userId:'user_local'};}};
 const service=load('lib/publications/agent-service.ts',{'@/lib/require-admin':guard,'@/lib/supabase/server':{getSupabaseServerClient:()=>db},'./agent-context':{buildPublicationAgentContext:async()=>ctx},'@/lib/integrations/publications-drive':{driveReadProvider:()=>{throw Error('Unexpected real Drive');}},'./ai/openai-provider':{openaiPublicationsProvider:()=>{throw Error('Unexpected real OpenAI');}}});
 const usage={input_tokens:100,output_tokens:20,estimated_cost_eur:0,model:'gpt-4.1-mini-2025-04-14'};
 const providers={media:{list:async()=>{calls.push(['list']);return none?[]:[{...photo(),client_id:foreign?'foreign':client}];},download:async()=>bytes},ai:{analyze:async photos=>{calls.push(['analyze']);return {analyses:photos.map(p=>({id:p.id,analysis:photo().analysis})),usage};},generate:async c=>{calls.push(['generate',c]);return {content:output(c),usage};}}};return {service,providers,calls,uploads};
}
test('manual preparation commits one revision with two variants and a shared social asset',async()=>{const r=await runtime();const result=await r.service.preparePublication(project,publication,{allowRealAI:false},r.providers);assert.match(result.message,/soumis/);const args=r.calls.find(c=>c[0]==='publication_ai_finish')[1];assert.equal(args.p_derivatives.length,2);assert.equal(args.p_derivatives[0].asset_id,args.p_derivatives[1].asset_id);assert.equal(r.uploads.length,2);assert.equal(r.calls.filter(c=>c[0]==='analyze').length,1);assert.equal(r.calls.filter(c=>c[0]==='generate').length,1);});
test('a duplicate manual request does not call AI or Drive',async()=>{const r=await runtime({reused:true});await r.service.preparePublication(project,publication,{allowRealAI:false},r.providers);assert.equal(r.calls.length,1);});
test('real AI authorization absent stops before database, Drive and OpenAI',async()=>{const r=await runtime();assert.match((await r.service.preparePublication(project,publication,{allowRealAI:false})).message,/autorisé/);assert.equal(r.calls.length,0);});
test('missing media is auditable and does not call AI',async()=>{const r=await runtime({none:true});assert.match((await r.service.preparePublication(project,publication,{allowRealAI:false},r.providers)).message,/media_required/);assert.equal(r.calls.some(c=>c[0]==='analyze'||c[0]==='generate'),false);assert.equal(r.uploads.length,0);});
test('cross-client candidates fail before vision and submit no content',async()=>{const r=await runtime({foreign:true});await r.service.preparePublication(project,publication,{allowRealAI:false},r.providers);assert.equal(r.calls.some(c=>c[0]==='analyze'||c[0]==='publication_ai_finish'),false);assert.equal(r.calls.find(c=>c[0]==='publication_ai_fail')[1].p_cost,0);});
test('failed transaction cleans private uploads and records a sanitized conservative cost',async()=>{const r=await runtime({finishError:true});const result=await r.service.preparePublication(project,publication,{allowRealAI:false},r.providers);assert.match(result.message,/échouée/);assert.doesNotMatch(result.message,/secret/);assert.equal(r.calls.filter(c=>c[0]==='remove').length,2);assert.equal(r.calls.find(c=>c[0]==='publication_ai_fail')[1].p_cost,.1);});
test('regeneration receives the exact previous refusal',async()=>{const r=await runtime({rejected:true});await r.service.preparePublication(project,publication,{allowRealAI:false},r.providers);assert.equal(r.calls.find(c=>c[0]==='generate')[1].rejection,'Changer le sujet');});
test('non-admin is denied before providers and storage',async()=>{const r=await runtime({deny:true});await assert.rejects(()=>r.service.preparePublication(project,publication,{allowRealAI:false},r.providers),/denied/);assert.equal(r.calls.length,0);});
test('server integrations alone hold credentials; no publisher, cron or image generation',()=>{for(const f of ['lib/integrations/publications-drive.ts','lib/integrations/publications-openai.ts','lib/publications/agent-service.ts','lib/publications/ai/openai-provider.ts'])assert.match(readFileSync(new URL('../'+f,import.meta.url),'utf8'),/import ['"]server-only['"]/);const drive=readFileSync(new URL('../lib/integrations/publications-drive.ts',import.meta.url),'utf8');assert.doesNotMatch(drive,/method:\s*['"](?:POST|PATCH|PUT|DELETE)/);assert.doesNotMatch(readFileSync(new URL('../supabase/migrations/20261005220029_publications_opportunity_agent.sql',import.meta.url),'utf8'),/update public.publication_settings|cron\.schedule|pg_net|http_post/i);});
test('OpenAI transport is strict, server-only, bounded, non-storing and metered using a simulated response',async()=>{const requests=[];const adapter=load('lib/integrations/publications-openai.ts',{}, {process:{env:{OPENAI_API_KEY:'fixture-secret'}},fetch:async(url,args)=>{requests.push({url,args});return {ok:true,json:async()=>({status:'completed',usage:{input_tokens:1000,output_tokens:100},output:[{content:[{type:'output_text',text:'{"fixture":true}'}]}]})};}});const r=await adapter.structuredResponse('Known instructions','Known input',{type:'object'});const body=JSON.parse(requests[0].args.body);assert.equal(body.store,false);assert.equal(body.text.format.strict,true);assert.equal(body.max_output_tokens,3000);assert.equal(body.model,'gpt-4.1-mini-2025-04-14');assert.equal(r.value.fixture,true);assert.equal(r.usage.input_tokens,1000);assert.equal(r.usage.estimated_cost_eur,.0007);assert.equal(requests[0].url,'https://api.openai.com/v1/responses');});
test('missing AI credential and provider error disclose no secrets',async()=>{const missing=load('lib/integrations/publications-openai.ts',{}, {fetch:async()=>{throw Error('Network must not be called');}});await assert.rejects(()=>missing.structuredResponse('','',{}),/credential unavailable/);const adapter=load('lib/integrations/publications-openai.ts',{}, {process:{env:{OPENAI_API_KEY:'fixture-secret'}},fetch:async()=>({ok:false})});await assert.rejects(()=>adapter.structuredResponse('','',{}),e=>e.message==='AI request failed'&&!e.message.includes('fixture-secret'));});
test('Drive adapter performs GET reads only within the configured folder and rejects foreign parents',async()=>{const requests=[];const adapter=load('lib/integrations/publications-drive.ts',{}, {process:{env:{GOOGLE_DRIVE_READ_ACCESS_TOKEN:'fixture-token'}},fetch:async(url,args)=>{requests.push({url,args});return {ok:true,json:async()=>url.searchParams.get('q')?{files:[{id:'drivefile00001',name:'Photo',modifiedTime:'2026-10-01T00:00:00Z',mimeType:'image/png',size:'1200',imageMediaMetadata:{width:800,height:400}}]}:{parents:['anotherfolder0001'],mimeType:'image/png',size:'1200',trashed:false}};}});const provider=adapter.driveReadProvider(),photos=await provider.list('folder00000001',client,project);assert.equal(photos.length,1);assert.equal(photos[0].client_id,client);assert.equal(photos[0].project_id,project);assert.ok(requests[0].url.searchParams.get('q').includes("'folder00000001' in parents"));await assert.rejects(()=>provider.download('drivefile00001','folder00000001'),/scope invalid/);assert.equal(requests.length,2);assert.ok(requests.every(r=>!r.args.method||r.args.method==='GET'));});
test('growth and emerging pages are opportunities even without low CTR; invalid metrics never qualify',async()=>{const {searchConsoleProvider}=load('lib/publications/opportunities/search-console.ts');const row={query:'couverture',service:'Couverture',impressions:1000,clicks:100,position:8,previousImpressions:500,measuredAt:'2026-10-01',local:false};const rows=await searchConsoleProvider([row,{...row,previousImpressions:1000,page:'/couverture',previousClicks:50},{...row,clicks:NaN},{...row,measuredAt:'bad'},{...row,clicks:-1}]).collect(context);assert.equal(rows.length,2);});
function contextSetup({scope=true,foreign=false,deny=false}={}){const calls=[];const rows={publication_agent_projects:{project_id:project,client_id:client,agent_id:'agent',enabled:true,rights_confirmed:true,drive_folder_id:'folder00000001',verified_services:['Couverture'],editorial_rules:'Objectif du projet'},agents:{id:'agent',name:'Agent Publications',enabled:true,publication_specialist:true,instructions:'Prudence',agent_scope:'project'},projects:{id:project,client_id:client,name:'Projet local',type:'Réseaux sociaux'},clients:{id:client,name:'Client local',activity:'Artisan',notes:'Notes confirmées',website:null,geographic_area:null},agent_client_assignments:{client_instructions:'Instructions client'},publication_calendar_slots:{client_id:client,project_id:project,local_date:'2026-11-02'},publication_client_settings:{editorial_brief:'Brief client'},publication_revisions:[{id:'revision',internal_title:'Sujet précédent'}],publication_variants:[{revision_id:'revision',text_content:'Texte précédent'},{revision_id:'another-project',text_content:'Texte hors projet'}],publication_reviews:[{revision_id:'revision',decision:'rejected',reason:'Changer la photo'}],publication_media_uses:[]};const db={from:table=>{calls.push(['from',table]);const q={select:()=>q,eq:(k,v)=>{calls.push(['eq',table,k,v]);return q;},order:()=>q,single:async()=>({data:rows[table]}),maybeSingle:async()=>({data:rows[table]}),range:async()=>({data:rows[table]})};return q;}};const contextModule=load('lib/publications/agent-context.ts',{'@/lib/require-admin':{requireAdmin:async()=>{if(deny)throw Error('denied');}},'@/lib/supabase/server':{getSupabaseServerClient:()=>db},'@/lib/agents/scope':{validateAgentContext:async()=>scope},'./workspace':{getWorkspace:async()=>({publication:{client_id:foreign?'foreign':client,project_id:project},reviews:[],variants:[]})},'./planning':{getProjectCadence:async()=>({timezone:'Europe/Paris'}),planningRows:async factory=>(await factory().range(0,99)).data}});return {contextModule,calls};}
test('agent context combines client, project, reserved date, editorial rules and scoped history',async()=>{const r=contextSetup(),c=await r.contextModule.buildPublicationAgentContext(project,publication);assert.equal(c.client.notes,'Notes confirmées');assert.equal(c.project.id,project);assert.equal(c.slot.local_date,'2026-11-02');assert.equal(c.cadence.timezone,'Europe/Paris');assert.equal(c.historyVariants.length,1);assert.equal(c.historyReviews.length,1);assert.ok(c.rules.includes('Instructions client'));assert.ok(c.opportunities.length);assert.ok(r.calls.some(c=>c[0]==='eq'&&c[1]==='publication_revisions'&&c[2]==='project_id'&&c[3]===project));});
test('agent context rejects mismatched publication, unassigned agent and non-admin',async()=>{for(const options of [{scope:false},{foreign:true},{deny:true}]){const r=contextSetup(options);await assert.rejects(()=>r.contextModule.buildPublicationAgentContext(project,publication));if(options.deny)assert.equal(r.calls.length,0);}});
test('Drive repeated pagination tokens fail closed and empty pages cannot loop indefinitely',async()=>{let calls=0;const adapter=load('lib/integrations/publications-drive.ts',{}, {process:{env:{GOOGLE_DRIVE_READ_ACCESS_TOKEN:'fixture-token'}},fetch:async()=>{calls++;return {ok:true,json:async()=>({files:[],nextPageToken:'repeated'})};}});await assert.rejects(()=>adapter.driveReadProvider().list('folder00000001',client,project),/pagination invalid/);assert.equal(calls,2);calls=0;const bounded=load('lib/integrations/publications-drive.ts',{}, {process:{env:{GOOGLE_DRIVE_READ_ACCESS_TOKEN:'fixture-token'}},fetch:async()=>{calls++;return {ok:true,json:async()=>({files:[],nextPageToken:String(calls)})};}});assert.equal((await bounded.driveReadProvider().list('folder00000001',client,project)).length,0);assert.equal(calls,5);});
