import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {test} from 'node:test';
import {Worker} from 'node:worker_threads';
import {executeLocalSql} from './helpers/local-postgres.mjs';
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
test('Lot 4 SQL: nine migrations, two rebuilds, budget, photo-first, immutable history, rollback and concurrency',{skip:!process.env.PUBLICATIONS_AGENT_TEST_DATABASE_URL?'Dedicated local DB not configured':false},async()=>{
 const url=new URL(process.env.PUBLICATIONS_AGENT_TEST_DATABASE_URL);assert.equal(url.hostname,'127.0.0.1');assert.equal(url.pathname,'/publications_agent_test');
 const env={...process.env,PGHOST:'127.0.0.1',PGHOSTADDR:'127.0.0.1',PGPORT:url.port,PGUSER:url.username,PGDATABASE:'publications_agent_test',PGPASSWORD:'',PGOPTIONS:''};delete env.PGSERVICE;delete env.PGSERVICEFILE;
 const files=readdirSync(new URL('../supabase/migrations/',import.meta.url)).filter(f=>/^20261005.*\.sql$/.test(f)).sort();assert.equal(files.length,9);
 const foundation='begin;'+read('supabase/local/remote-schema.sql')+'reset role;'+read('supabase/tests/remote-replay-helpers.sql')+read('supabase/tests/remote-replay-fixtures.sql')+`create schema storage authorization postgres;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);alter table storage.buckets owner to postgres;set local role postgres;`+files.slice(0,6).map(f=>read('supabase/migrations/'+f)).join('\n')+read('supabase/tests/publications-review-legacy-fixture.sql')+'set local role postgres;set constraints all immediate;'+files.slice(6).map(f=>read('supabase/migrations/'+f)).join('\n')+'reset role;set constraints all deferred;';
 const command=process.env.PUBLICATIONS_AGENT_TEST_PSQL??'psql',checks=read('supabase/tests/publications-agent.sql');
 for(let i=1;i<=2;i++){const result=executeLocalSql(command,env,foundation+checks+"select 'AGENT_CHECKS='||passed from pg_temp.remote_replay;rollback;");assert.ifError(result.error);assert.equal(result.status,0,result.stderr+'\n'+result.stdout.slice(-2000));console.log(result.stdout.match(/AGENT_CHECKS=\d+/)?.[0]+`; rebuild ${i}/2 passed`);}
 try{
  const setup=executeLocalSql(command,env,foundation+checks+'commit;');assert.equal(setup.status,0,setup.stderr);
  const sql=`begin;set local role service_role;select public.publication_ai_begin((select publication_id from public.publication_calendar_slots where project_id='30000000-0000-4000-8000-000000000001' order by local_date desc limit 1),null,'user_local');select pg_sleep(.25);commit;`;
  const run=()=>new Promise((resolve,reject)=>{const w=new Worker(`const {parentPort,workerData}=require('node:worker_threads');import(workerData.helper).then(({executeLocalSql})=>parentPort.postMessage(executeLocalSql(workerData.command,workerData.env,workerData.sql)));`,{eval:true,workerData:{helper:new URL('./helpers/local-postgres.mjs',import.meta.url).href,command,env,sql}});w.once('message',resolve);w.once('error',reject);});
  for(const r of await Promise.all([run(),run()]))assert.equal(r.status,0,r.stderr);
  const result=executeLocalSql(command,env,`select 'RACE_RUNS='||count(*) from public.publication_ai_runs where publication_id=(select publication_id from public.publication_calendar_slots where project_id='30000000-0000-4000-8000-000000000001' order by local_date desc limit 1);select 'RACE_EVENTS='||count(*) from public.publication_events where action='publication.preparation_started' and resource_id=(select publication_id from public.publication_calendar_slots where project_id='30000000-0000-4000-8000-000000000001' order by local_date desc limit 1);`);
  assert.equal(result.status,0,result.stderr);assert.match(result.stdout,/RACE_RUNS=1/);assert.match(result.stdout,/RACE_EVENTS=1/);console.log('Two simultaneous preparations: one reserved run and one start event; no AI call.');
  const cap=executeLocalSql(command,env,`update public.agents set max_monthly_budget_eur=(select coalesce(sum(case when status='processing' then reserved_cost_eur else estimated_cost_eur end),0)+.15 from public.publication_ai_runs where agent_id=agents.id) where publication_specialist;`);assert.equal(cap.status,0,cap.stderr);
  const budgetRun=offset=>new Promise((resolve,reject)=>{const sql=`begin;set local role service_role;select public.publication_ai_begin((select publication_id from public.publication_calendar_slots where project_id='30000000-0000-4000-8000-000000000001' order by local_date offset ${offset} limit 1),null,'user_local');select pg_sleep(.25);commit;`;const w=new Worker(`const {parentPort,workerData}=require('node:worker_threads');import(workerData.helper).then(({executeLocalSql})=>parentPort.postMessage(executeLocalSql(workerData.command,workerData.env,workerData.sql)));`,{eval:true,workerData:{helper:new URL('./helpers/local-postgres.mjs',import.meta.url).href,command,env,sql}});w.once('message',resolve);w.once('error',reject);});
  const raced=await Promise.all([budgetRun(4),budgetRun(5)]);assert.equal(raced.filter(r=>r.status===0).length,1);assert.match(raced.find(r=>r.status!==0).stderr,/Budget limit reached/);
  const bounded=executeLocalSql(command,env,`select 'BUDGET_SAFE='||(a.max_monthly_budget_eur >= (select sum(case when r.status='processing' then r.reserved_cost_eur else r.estimated_cost_eur end) from public.publication_ai_runs r where r.agent_id=a.id)) from public.agents a where publication_specialist;`);assert.equal(bounded.status,0,bounded.stderr);assert.match(bounded.stdout,/BUDGET_SAFE=true/);console.log('Two different publications competing for the monthly budget: one admitted, one refused; cap respected.');
 }finally{const result=executeLocalSql(command,env,'drop schema if exists publications_private cascade;drop schema if exists agent_scope_private cascade;drop schema if exists storage cascade;drop schema public cascade;create schema public authorization postgres;');assert.equal(result.status,0,result.stderr);}
});
