import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {test} from 'node:test';
import vm from 'node:vm';
import ts from 'typescript';
import * as jsx from 'react/jsx-runtime';
import {renderToStaticMarkup} from 'react-dom/server';
function load(path,mocks){const exports={};const code=ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;vm.runInNewContext(code,{exports,require:name=>name==='react/jsx-runtime'?jsx:mocks[name]??(()=>{throw Error('Unexpected import '+name)})()});return exports;}
const project='30000000-0000-4000-8000-000000000001',publication='40000000-0000-4000-8000-000000000001';
function actionSetup(deny=false){const calls=[];const actions=load('app/(cockpit)/publications/agent-actions.ts',{'next/cache':{revalidatePath:path=>calls.push(['revalidate',path])},'@/lib/require-admin':{requireAdmin:async()=>{if(deny)throw Error('denied');return {userId:'user_local'};}},'@/lib/publications/agent-service':{configurePublicationsAgent:async()=>({message:'Configured'}),preparePublication:async(...args)=>{calls.push(['prepare',...args]);return {message:'Prepared'};}},'@/lib/publications/validation':{isPublicationUuid:s=>typeof s==='string'&&/^[a-f0-9-]{36}$/.test(s)}});return {actions,calls};}
const form=()=>{const f=new FormData();f.set('project_id',project);f.set('publication_id',publication);return f;};
test('Server Action demands explicit authorization for one exact placeholder',async()=>{const r=actionSetup(),f=form();assert.match((await r.actions.prepareAgentAction({},f)).message,/Autorisez/);assert.equal(r.calls.length,0);f.set('authorize_ai','on');assert.equal((await r.actions.prepareAgentAction({},f)).message,'Prepared');assert.equal(r.calls[0][1],project);assert.equal(r.calls[0][2],publication);assert.equal(r.calls[0][3].allowRealAI,true);assert.ok(r.calls.some(c=>c[0]==='revalidate'&&c[1]==='/publications/review'));});
test('Server Action rejects duplicate checkbox values and invalid publication IDs',async()=>{for(const mutate of [f=>{f.append('authorize_ai','on');},f=>f.set('publication_id','bad')]){const r=actionSetup(),f=form();f.set('authorize_ai','on');mutate(f);assert.match((await r.actions.prepareAgentAction({},f)).message,/Autorisez/);assert.equal(r.calls.length,0);}});
test('unauthorized Server Actions do not reach preparation/configuration',async()=>{const r=actionSetup(true);await assert.rejects(()=>r.actions.prepareAgentAction({},form()),/denied/);await assert.rejects(()=>r.actions.configureAgentAction({},form()),/denied/);assert.equal(r.calls.length,0);});
test('project form is limited to one placeholder and requires an unchecked authorization checkbox',()=>{const forms=load('components/publications/agent-forms.tsx',{'react':{useActionState:()=>[{},()=>{},false]},'@/app/(cockpit)/publications/agent-actions':{configureAgentAction:()=>{},prepareAgentAction:()=>{}}});const html=renderToStaticMarkup(jsx.jsx(forms.AgentPrepareForm,{projectId:project,placeholders:[{id:publication,date:'2026-11-02'}]}));assert.match(html,/Préparer les publications/);assert.match(html,/name="publication_id"/);assert.match(html,/name="authorize_ai"/);assert.match(html,/required/);assert.doesNotMatch(html,/checked|multiple/);const regen=renderToStaticMarkup(jsx.jsx(forms.AgentPrepareForm,{projectId:project,publicationId:publication,regenerate:true}));assert.match(regen,/Régénérer/);});
test('configuration reload reflects both activation and confirmed media rights',()=>{const forms=load('components/publications/agent-forms.tsx',{'react':{useActionState:()=>[{},()=>{},false]},'@/app/(cockpit)/publications/agent-actions':{configureAgentAction:()=>{},prepareAgentAction:()=>{}}});const html=renderToStaticMarkup(jsx.jsx(forms.AgentConfigurationForm,{projectId:project,config:{enabled:true,rights_confirmed:true,drive_folder_id:'folder00000001',verified_services:['Couverture'],editorial_rules:'Objectif'}}));assert.equal((html.match(/checked=""/g)??[]).length,2);assert.match(html,/Couverture/);assert.match(html,/folder00000001/);});
function reviewSetup(rows=[],deny=false){const p=({children})=>jsx.jsx('section',{children});return load('app/(cockpit)/publications/review/page.tsx',{'next/link':{default:({href,children})=>jsx.jsx('a',{href,children})},'@/lib/require-admin':{requireAdmin:async()=>{if(deny)throw Error('denied');}},'@/lib/publications/data':{listPublications:async()=>rows},'@/lib/publications/workspace':{getWorkspace:async()=>({variants:[{id:'variant',revision_id:'revision',platform:'facebook',text_content:'Texte prudent'}],links:[{variant_id:'variant',asset_id:'asset'}],assets:[{id:'asset',preview:'http://127.0.0.1/fixture.jpg'}]})},'@/lib/publications/agent-data':{getGenerationDetails:async()=>({selected_opportunity:{subject:'Couverture',score:90,reasons:['Photo compatible']},generation_summary:'Validation humaine requise.'})},'@/lib/publications/editor':{platformLabels:{facebook:'Facebook'}},'@/components/publications/workflow-forms':{PublicationReviewForm:()=>jsx.jsx('button',{children:'Approuver ou refuser'})},'@/components/ui/primitives':{Panel:p,PageHeading:()=>null}});}
test('review route renders a clean empty state without creating content',async()=>{assert.match(renderToStaticMarkup(await reviewSetup().default()),/Aucune publication en attente/);});
test('review route presents client/project/date, evidence, image, variant and decisions',async()=>{const html=renderToStaticMarkup(await reviewSetup([{id:publication,status:'pending_review',current_revision_id:'revision',subject:'Sujet',client:{name:'Client local'},project:{name:'Projet social'},target_date:'2026-11-02'}]).default());for(const s of ['Client local','Projet social','2026-11-02','90/100','Photo compatible','fixture.jpg','Texte prudent','Approuver ou refuser'])assert.ok(html.includes(s),s);});
test('review route denies a non-admin before reading data',async()=>assert.rejects(()=>reviewSetup([],true).default(),/denied/));
