import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {test} from 'node:test';
import {Worker} from 'node:worker_threads';
import {executeLocalSql} from './helpers/local-postgres.mjs';
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
test('Lot 3 SQL: clean reconstruction twice, permissions, planning, rollback and real concurrent sessions',{skip:!process.env.PUBLICATIONS_CALENDAR_TEST_DATABASE_URL?'Dedicated local DB not configured':false},async()=>{
 const url=new URL(process.env.PUBLICATIONS_CALENDAR_TEST_DATABASE_URL);assert.equal(url.hostname,'127.0.0.1');assert.equal(url.pathname,'/publications_calendar_test');
 const env={...process.env,PGHOST:'127.0.0.1',PGHOSTADDR:'127.0.0.1',PGPORT:url.port,PGUSER:url.username,PGDATABASE:'publications_calendar_test',PGPASSWORD:'',PGOPTIONS:''};delete env.PGSERVICE;delete env.PGSERVICEFILE;
 const files=readdirSync(new URL('../supabase/migrations/',import.meta.url)).filter(f=>/^20261005.*\.sql$/.test(f)&&!f.includes('opportunity_agent')).sort();assert.equal(files.length,8);
 const foundation='begin;'+read('supabase/local/remote-schema.sql')+'reset role;'+read('supabase/tests/remote-replay-helpers.sql')+read('supabase/tests/remote-replay-fixtures.sql')+`create schema storage authorization postgres;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);alter table storage.buckets owner to postgres;set local role postgres;`+files.slice(0,6).map(f=>read('supabase/migrations/'+f)).join('\n')+read('supabase/tests/publications-review-legacy-fixture.sql')+'set local role postgres;set constraints all immediate;'+read('supabase/migrations/'+files[6])+`create temporary table legacy_publication_snapshot as select to_jsonb(p) value from public.publications p;`+read('supabase/migrations/'+files[7])+'reset role;set constraints all deferred;';
 const command=process.env.PUBLICATIONS_CALENDAR_TEST_PSQL??'psql';
 for(let i=1;i<=2;i++){const result=executeLocalSql(command,env,foundation+read('supabase/tests/publications-calendar.sql')+"select 'CALENDAR_CHECKS='||passed from pg_temp.remote_replay;rollback;");assert.ifError(result.error);assert.equal(result.status,0,result.stderr+'\n'+result.stdout.slice(-2500));assert.match(result.stdout,/CALENDAR_CHECKS=\d+/);console.log(result.stdout.match(/CALENDAR_CHECKS=\d+/)[0]+`; rebuild ${i}/2 passed`);}
 try{
  const setup=executeLocalSql(command,env,foundation+read('supabase/tests/publications-calendar.sql')+'commit;');assert.equal(setup.status,0,setup.stderr);
  const sql=`begin;set local role service_role;select public.publication_ensure_calendar('30000000-0000-4000-8000-000000000001','2027-01-04',true,'user_local');select pg_sleep(0.25);commit;`;
  const run=(statement=sql)=>new Promise((resolve,reject)=>{const w=new Worker(`const {parentPort,workerData}=require('node:worker_threads');import(workerData.helper).then(({executeLocalSql})=>parentPort.postMessage(executeLocalSql(workerData.command,workerData.env,workerData.sql)));`,{eval:true,workerData:{helper:new URL('./helpers/local-postgres.mjs',import.meta.url).href,command,env,sql:statement}});w.once('message',resolve);w.once('error',reject);});
  for(const r of await Promise.all([run(),run()]))assert.equal(r.status,0,r.stderr);
  const r=executeLocalSql(command,env,`select 'RACE_SLOTS='||count(*) from public.publication_calendar_slots where project_id='30000000-0000-4000-8000-000000000001' and editorial_week between '2027-01-04' and '2027-01-25';select 'RACE_PUBLICATIONS='||count(*) from public.publications where project_id='30000000-0000-4000-8000-000000000001' and editorial_week between '2027-01-04' and '2027-01-25';select 'RACE_EVENTS='||count(*) from public.publication_events e join public.publications p on p.id=e.resource_id where e.action='publication.placeholder_created' and p.editorial_week between '2027-01-04' and '2027-01-25';`);
  assert.equal(r.status,0,r.stderr);for(const key of ['RACE_SLOTS','RACE_PUBLICATIONS','RACE_EVENTS'])assert.match(r.stdout,new RegExp(key+'=8'));
  console.log('Two simultaneous sessions: exactly 8 slots, 8 placeholders and 8 creation events.');
  const manual=`begin;set local role service_role;select public.publication_save_draft(null,null,'10000000-0000-4000-8000-000000000001','30000000-0000-4000-8000-000000000001','Manual race','A','S','2027-02-22',null,null,'[{"platform":"facebook","text_content":"F"}]','user_local');select pg_sleep(0.25);commit;`;
  const reserve=`begin;set local role service_role;select public.publication_ensure_calendar('30000000-0000-4000-8000-000000000001','2027-02-22',false,'user_local');select pg_sleep(0.25);commit;`;
  for(const result of await Promise.all([run(manual),run(reserve)]))assert.equal(result.status,0,result.stderr);
  const bound=executeLocalSql(command,env,`select 'MANUAL_RACE_BOUND='||count(*) from public.publication_calendar_slots s join public.publications p on s.publication_id=p.id where p.subject='Manual race' and s.local_date=p.target_date;select 'MANUAL_RACE_SLOTS='||count(*) from public.publication_calendar_slots where project_id='30000000-0000-4000-8000-000000000001' and editorial_week between '2027-02-22' and '2027-03-15';`);
  assert.equal(bound.status,0,bound.stderr);assert.match(bound.stdout,/MANUAL_RACE_BOUND=1/);assert.match(bound.stdout,/MANUAL_RACE_SLOTS=8/);console.log('Concurrent manual draft and planner: one bound publication, 8 slots, no deadlock.');
 }finally{const r=executeLocalSql(command,env,'drop schema if exists publications_private cascade;drop schema if exists agent_scope_private cascade;drop schema if exists storage cascade;drop schema public cascade;create schema public authorization postgres;');assert.equal(r.status,0,r.stderr);}
});
