import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
function load(path,mocks={}){const exports={};const code=ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(code,{exports,FormData,File,Uint8Array,Date,Set,console,require:n=>{if(n==='server-only')return {};if(n==='./review-decisions')return reviewModel;if(n==='./media-rule')return mediaRule;if(n==='./project-channels')return projectChannels;if(n==='./channels')return channelsModule;if(n in mocks)return mocks[n];throw Error(n);}});return exports;}
const reviewModel=load('lib/publications/review-decisions.ts');
const channelsModule=load('lib/publications/channels.ts',{'./types':load('lib/publications/types.ts'),'./editor':{platformLabels:{facebook:'Facebook',instagram:'Instagram',google_business_profile:'Google Business Profile'}}}),legacyChannels=load('lib/publications/legacy-channels.ts');
// No explicit channel row in these fixtures: legacy fallback and no channel lock.
const projectChannels={publicationChannelLock:async()=>null,getPublicationProjectChannels:async project=>channelsModule.publicationCapabilities(legacyChannels.legacyPublicationChannelsForType(project.type),'legacy')};
const mediaRule=load('lib/publications/media-rule.ts',{'./editor':{platformLabels:{facebook:'Facebook',instagram:'Instagram',google_business_profile:'Google Business Profile'}}});
const types=load('lib/publications/types.ts');const validation=load('lib/publications/validation.ts',{'./types':types});const editor=load('lib/publications/editor.ts',{'./validation':validation,'./types':types});
const id='10000000-0000-4000-8000-000000000001';
function form(){const f=new FormData();for(const [k,v] of Object.entries({client_id:id,project_id:id,title:'Titre',angle:'Angle',source:'Source',facebook_enabled:'on',facebook_text:'Texte',facebook_title:'Titre canal',facebook_cta:'Nous contacter'}))f.set(k,v);return f;}
test('manual form supports optional target/slot and closed channel metadata',()=>{const p=editor.parseEditorialForm(form());assert.equal(p.title,'Titre');assert.equal(p.slot,null);assert.equal(p.target_date,null);assert.equal(p.variants[0].metadata.cta,'Nous contacter');assert.equal(p.publication_id,null);});
test('invalid dates, empty variants, stale identifiers, duplicate fields and excess assets rejected',()=>{for(const [key,value] of [['target_date','2026-02-30'],['week','2026-10-06'],['slot','3'],['project_id','bad'],['source',''],['facebook_enabled','']]){const f=form();f.set(key,value);assert.equal(editor.parseEditorialForm(f),null);}const f=form();f.append('client_id',id);assert.equal(editor.parseEditorialForm(f),null);const a=form();a.append('facebook_assets',id);a.append('facebook_assets',id);assert.equal(editor.parseEditorialForm(a),null);});
test('only social or GBP projects expose the appropriate platforms (legacy fallback, unchanged)',()=>{const platforms=type=>channelsModule.publicationCapabilities(legacyChannels.legacyPublicationChannelsForType(type),'legacy').platforms;assert.equal(platforms('Réseaux sociaux').join(','),'facebook,instagram');assert.equal(platforms('Google Business Profile').join(','),'google_business_profile');assert.equal(platforms('Google Ads').length,0);assert.equal(editor.allowedPlatforms,undefined,'the type → platforms rule left the editor');});
test('private image constraints, temporary signed URLs and magic signatures',()=>{assert.equal(editor.IMAGE_BUCKET,'publication-images');assert.equal(editor.IMAGE_URL_TTL,120);assert.equal(editor.MAX_IMAGE_BYTES,786432);assert.equal(editor.imageMime(new Uint8Array(12)),null);assert.equal(editor.imageMime(Uint8Array.from([137,80,78,71,13,10,26,10,0,0,0,0])),'image/png');});
test('all workspace operations reject non-admin before accessing DB or storage',async()=>{const workspace=load('lib/publications/workspace.ts',{'node:crypto':{},'@/lib/require-admin':{requireAdmin:async()=>{throw Error('denied');}},'@/lib/supabase/server':{getSupabaseServerClient:()=>{throw Error('storage reached');}},'./validation':validation,'./editor':editor});for(const [fn,args] of [['getWorkspace',[id]],['saveDraft',[form()]],['submitOrReview',[form()]],['uploadImage',[form()]],['publicationSummaries',[[id]]]])await assert.rejects(()=>workspace[fn](...args),/denied/);});
test('Lot 2 has no delivery/generation API and settings writes are absent',()=>{const source=readFileSync('lib/publications/workspace.ts','utf8');assert.doesNotMatch(source,/\.from\("publication_(?:jobs|deliveries|settings)"\)\.(?:insert|update)|getPublicUrl|\.rpc\("publication_review"|openai|graph\.facebook|googleapis/);const sql=readFileSync('supabase/migrations/20261005000005_publications_manual_workspace.sql','utf8');assert.doesNotMatch(sql,/update public\.publication_settings|insert into public\.publication_jobs|cron\.schedule/i);assert.match(sql,/publication-images.*false/s);});
function repository({project={id,client_id:id,type:'Réseaux sociaux'},registerError=null}={}){
 const calls=[];const root={id,client_id:id,current_revision_id:id};const asset={id,client_id:id,storage_path:`${id}/${id}/${id}`,provenance:'Owned',mime_type:'image/png'};
 const storage={upload:async(path,bytes,options)=>{calls.push(['upload',path,options]);return {error:null};},remove:async(paths)=>{calls.push(['remove',paths]);return {error:null};},createSignedUrl:async(path,ttl)=>{calls.push(['sign',path,ttl]);return {data:{signedUrl:'temporary-preview'},error:null};}};
 const db={storage:{from:bucket=>{calls.push(['bucket',bucket]);return storage;}},rpc:async(name,args)=>{calls.push(['rpc',name,args]);return {data:id,error:registerError};},from:table=>{const q={select:()=>q,eq:()=>q,in:(column,values)=>{calls.push(['in',table,column,values]);return q;},like:()=>q,order:()=>q,single:async()=>({data:root,error:null}),maybeSingle:async()=>({data:table==='projects'?project:root,error:null}),range:async(start)=>{calls.push(['range',table,start]);const data=table==='publication_assets'?[asset]:table==='publication_events'?(start===0?Array.from({length:100},(_,i)=>({id:String(i)})):[{id:'last',action:'publication.media_uploaded',metadata:{asset_id:id}}]):[];return {data,error:null};}};return q;}};
 const service=load('lib/publications/workspace.ts',{'node:crypto':{randomUUID:()=>id,createHash:()=>({update:()=>({digest:()=> 'a'.repeat(64)})})},'@/lib/require-admin':{requireAdmin:async()=>({userId:'user_admin'})},'@/lib/supabase/server':{getSupabaseServerClient:()=>db},'./validation':validation,'./editor':editor});return {service,calls};
}
test('valid project creates a single manual RPC; missing or incompatible project never mutates',async()=>{const r=repository();assert.equal((await r.service.saveDraft(form())).id,id);assert.equal(r.calls.find(c=>c[0]==='rpc')[1],'publication_save_draft');assert.equal(r.calls.find(c=>c[0]==='rpc')[2].p_actor_id,'user_admin');for(const project of [null,{type:'Google Business Profile'}]){const bad=repository({project});assert.ok((await bad.service.saveDraft(form())).message);assert.equal(bad.calls.filter(c=>c[0]==='rpc').length,0);}});
test('workspace paginates journal and signs private media for 120 seconds',async()=>{const r=repository();const w=await r.service.getWorkspace(id);assert.equal(w.events.length,101);assert.equal(w.assets[0].preview,'temporary-preview');assert.ok(r.calls.some(c=>c[0]==='range'&&c[1]==='publication_events'&&c[2]===100));assert.ok(r.calls.some(c=>c[0]==='sign'&&c[2]===120));assert.ok(r.calls.some(c=>c[0]==='bucket'&&c[1]==='publication-images'));
 assert.ok(r.calls.some(c=>c[0]==='in'&&c[1]==='publication_assets'&&c[2]==='id'&&c[3].includes(id)),'media found through the audited upload relation, not the storage path');});
test('upload uses private storage, rights and RPC audit; failed registration cleans up object',async()=>{const f=new FormData();f.set('publication_id',id);f.set('revision_id',id);f.set('rights','on');f.set('provenance','Owned');f.set('image',new File([Uint8Array.from([137,80,78,71,13,10,26,10,0,0,0,0])],'ignored.png',{type:'image/png'}));const r=repository();assert.match((await r.service.uploadImage(f)).message,/ajoutée/);assert.ok(r.calls.some(c=>c[0]==='upload'&&c[2].upsert===false));assert.ok(r.calls.some(c=>c[0]==='rpc'&&c[1]==='publication_register_image'));const failed=repository({registerError:{code:'40001'}});await failed.service.uploadImage(f);assert.ok(failed.calls.some(c=>c[0]==='remove'));f.delete('rights');const invalid=repository();await invalid.service.uploadImage(f);assert.equal(invalid.calls.length,0);});
