import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import React from 'react';
import * as jsx from 'react/jsx-runtime';
import {renderToStaticMarkup} from 'react-dom/server';
function load(path,mocks={}){const exports={};const code=ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;vm.runInNewContext(code,{exports,FormData,Date,Intl,Set,console,require:n=>{if(n==='server-only')return {};if(n==='react/jsx-runtime')return jsx;if(n in mocks)return mocks[n];throw Error(n);}});return exports;}
const types=load('lib/publications/types.ts'),validation=load('lib/publications/validation.ts',{'./types':types}),editor=load('lib/publications/editor.ts',{'./types':types,'./validation':validation});
const engine=load('lib/publications/calendar.ts',{'./editor':editor});const client={id:'10000000-0000-4000-8000-000000000001'},project={id:'30000000-0000-4000-8000-000000000001',client_id:client.id,type:'Réseaux sociaux'};
const cadence={...engine.defaultCadence(project.type),enabled:true,auto_create_slots:true},period={start_week:'2026-10-12'};
test('two slots/week and four-week horizon with Paris summer and winter offsets',()=>{const slots=engine.buildEditorialCalendar(client,project,cadence,period);assert.equal(slots.length,8);assert.equal(slots[0].scheduled_for,'2026-10-12T10:00:00.000Z');assert.equal(slots[4].scheduled_for,'2026-10-26T11:00:00.000Z');assert.equal(slots[1].local_date,'2026-10-16');assert.equal(slots[7].editorial_week,'2026-11-02');assert.equal(new Set(slots.map(s=>s.key)).size,8);});
test('week rollover, leap dates, month boundaries and Paris midnight',()=>{assert.equal(engine.editorialMonday('2027-01-03'),'2026-12-28');assert.equal(engine.parisToday(new Date('2026-10-05T22:30:00Z')),'2026-10-06');assert.equal(engine.calendarPeriod('2028-02-15','month').to,'2028-02-29');assert.equal(engine.validDate('2026-02-30'),false);});
test('DST gaps rejected and ambiguous autumn time agrees with PostgreSQL',()=>{assert.equal(engine.localInstant('2026-03-29','02:30','Europe/Paris'),null);assert.equal(engine.localInstant('2026-10-25','02:30','Europe/Paris'),'2026-10-25T01:30:00.000Z');});
test('safe defaults, approval required and strict cadence validation',()=>{const c=engine.defaultCadence(null);assert.equal(c.enabled,false);assert.equal(c.auto_create_slots,false);assert.equal(c.require_manual_approval,true);assert.equal(engine.buildEditorialCalendar(client,project,c,period).length,0);for(const change of [{posts_per_week:3},{preferred_weekdays:[1,1]},{timezone:'Invalid'},{planning_horizon_weeks:13},{require_manual_approval:false},{unexpected:true}])assert.equal(engine.validateCadence({...cadence,...change}),null);});
test('reruns reserve identical identities without moving existing reservations',()=>{const initial=engine.buildEditorialCalendar(client,project,cadence,period);const existing=initial.map((s,i)=>({...s,id:'reservation-'+i,cadence_id:'cadence',publication_id:null,created_at:''}));const next=engine.buildEditorialCalendar(client,project,{...cadence,preferred_times:['14:00','14:00']},period,[],existing);assert.equal(next.filter(s=>s.state==='missing').length,0);assert.equal(next[0].local_time,'12:00');assert.equal(next.map(s=>s.key).join(','),initial.map(s=>s.key).join(','));});
test('existing manual date causes conflict, no silent reschedule, cross-client rejected',()=>{const p={id:'pub',client_id:client.id,project_id:project.id,editorial_week:'2026-10-12',slot:1,target_date:'2026-10-13'};assert.equal(engine.buildEditorialCalendar(client,project,cadence,period,[p])[0].state,'conflict');assert.equal(p.target_date,'2026-10-13');assert.throws(()=>engine.buildEditorialCalendar({id:'other'},project,cadence,period),/Périmètre/);assert.throws(()=>engine.buildEditorialCalendar(client,project,cadence,{start_week:'2026-10-13'}));assert.throws(()=>engine.buildEditorialCalendar(client,project,cadence,{...period,weeks:13}));});
test('GBP cadence is independent, one slot and appropriate channel',()=>{const gp={...project,id:'GBP',type:'Google Business Profile'},c={...engine.defaultCadence(gp.type),enabled:true,auto_create_slots:true};const slots=engine.buildEditorialCalendar(client,gp,c,period);assert.equal(slots.length,4);assert.equal(slots[0].platforms.join(','),'google_business_profile');});
test('global calendar combines client/project/platform/status and week/month filters',()=>{const row={key:'one',date:'2026-10-12',time:'12:00',client_id:client.id,project_id:project.id,platforms:['facebook','instagram'],status:'draft'};const rows=[row,{...row,key:'two',client_id:'other',date:'2026-10-13',status:'approved'}];const base={from:'2026-10-12',to:'2026-10-18'};assert.equal(engine.filterCalendar(rows,base).length,2);assert.equal(engine.filterCalendar(rows,{...base,client:client.id,project:project.id,platform:'facebook',status:'draft'}).length,1);assert.equal(engine.filterCalendar(rows,{...base,platform:'google_business_profile'}).length,0);assert.equal(engine.filterCalendar(rows,{from:'2026-11-01',to:'2026-11-30'}).length,0);});
test('planned and published require actual deliveries, errors remain visible',()=>{const p={id:'p',status:'approved'};assert.equal(engine.entryStatus(p,[]),'approved');assert.equal(engine.entryStatus(p,[{publication_id:'p',status:'scheduled'}]),'scheduled');assert.equal(engine.entryStatus(p,[{publication_id:'p',status:'published'}]),'published');assert.equal(engine.entryStatus(p,[{publication_id:'p',status:'uncertain'}]),'error');assert.equal(engine.entryStatus(undefined,[]),'free');});
test('placeholder form permits first revision, revision without root remains invalid',()=>{const f=new FormData();for(const [key,value] of Object.entries({publication_id:client.id,client_id:client.id,project_id:project.id,title:'T',angle:'A',source:'S',facebook_enabled:'on',facebook_text:'F'}))f.set(key,value);assert.equal(editor.parseEditorialForm(f).expected_revision_id,null);f.delete('publication_id');f.set('revision_id',client.id);assert.equal(editor.parseEditorialForm(f),null);});
const reviewModel=load('lib/publications/review-decisions.ts');
function planning(guard,db){return load('lib/publications/planning.ts',{'@/lib/require-admin':{requireAdmin:guard},'@/lib/supabase/server':{getSupabaseServerClient:()=>db},'@/lib/supabase/read-error':{safeSupabaseReadError:()=>({})},'./validation':validation,'./editor':editor,'./calendar':engine,'./review-decisions':reviewModel,'./data':{listPublications:async()=>[]},'@/lib/projects/data':{listProjects:async()=>[]}});}
function cadenceForm(){const f=new FormData();for(const [key,value] of Object.entries({project_id:project.id,posts_per_week:'2',day_0:'1',day_1:'5',time_0:'12:00',time_1:'12:00',timezone:'Europe/Paris',planning_horizon_weeks:'4'}))f.set(key,value);return f;}
test('checkbox FormData crosses the real action and service: absent=false, true/on=true, independent flags, reload',async()=>{
 let stored=null;let writes=0;const db={rpc:async(name,args)=>{assert.equal(name,'publication_save_cadence');writes++;stored={...args.p_config,project_id:project.id};return {data:project.id,error:null};},from:()=>{const q={select:()=>q,eq:()=>q,maybeSingle:async()=>({data:stored,error:null})};return q;}};
 const service=planning(async()=>({userId:'user_admin'}),db),actions=load('app/(cockpit)/publications/calendar/actions.ts',{'next/cache':{revalidatePath:()=>{}},'@/lib/require-admin':{requireAdmin:async()=>({userId:'user_admin'})},'@/lib/publications/planning':service,'@/lib/publications/validation':validation});
 const component=load('components/publications/planning-form.tsx',{'react':React,'@/app/(cockpit)/publications/calendar/actions':actions});
 for(const [enabled,reservation] of [[false,false],['true','true'],['on','on'],['true',false],[false,'true'],[false,false]]){
  const f=cadenceForm();if(enabled)f.set('enabled',enabled);if(reservation)f.set('auto_create_slots',reservation);
  const result=await actions.configurePlanning({message:''},f);assert.match(result.message,/Cadence enregistrée/);
  const reloaded=await service.getProjectCadence(project.id);assert.equal(reloaded.enabled,Boolean(enabled));assert.equal(reloaded.auto_create_slots,Boolean(reservation));
  const html=renderToStaticMarkup(React.createElement(component.PlanningForm,{projectId:project.id,cadence:reloaded,startWeek:period.start_week}));
  for(const [field,expected] of [['enabled',Boolean(enabled)],['auto_create_slots',Boolean(reservation)]]){const input=html.match(new RegExp('<input[^>]*name="'+field+'"[^>]*>'))?.[0];assert.ok(input);assert.match(input,/value="true"/);assert.equal(input.includes('checked=""'),expected);}
 }
 const before=writes;for(const values of [['unexpected'],['true','on']]){const f=cadenceForm();for(const value of values)f.append('enabled',value);assert.match((await actions.configurePlanning({message:''},f)).message,/invalide/);}assert.equal(writes,before);
});
test('every planning entrypoint rejects before DB access for non-admin',async()=>{const p=planning(async()=>{throw Error('denied');},null);for(const [fn,args] of [['getProjectCadence',[project.id]],['saveCadence',[project.id,cadence]],['ensureCalendar',[project.id,period.start_week,true]],['getCalendar',[{from:'2026-10-12',to:'2026-10-18'}]],['projectPlanningJobs',[project.id]],['planningRows',[()=>{throw Error('DB reached');}]]])await assert.rejects(()=>p[fn](...args),/denied/);});
test('manual planning RPC derives actor from admin and performs no publishing RPC',async()=>{const calls=[];const p=planning(async()=>({userId:'user_admin'}),{rpc:async(name,args)=>{calls.push({name,args});return {data:{slots_created:8,placeholders_created:8,conflicts:0},error:null};}});assert.equal((await p.ensureCalendar(project.id,period.start_week,true)).ok,true);assert.equal(calls[0].name,'publication_ensure_calendar');assert.equal(calls[0].args.p_actor_id,'user_admin');assert.equal(calls[0].args.p_placeholders,true);assert.equal((await p.saveCadence(project.id,{...cadence,require_manual_approval:false})).ok,false);assert.equal(calls.length,1);});
test('calendar page renders free slots and rejected revision truthfully; no delivery action',async()=>{const row={key:'slot',date:'2026-10-12',time:'12:00',timezone:'Europe/Paris',client_id:client.id,project_id:project.id,client_name:'Synthetic client',project_name:'Social',subject:'Content',platforms:['facebook','instagram'],status:'rejected',revision:1,validation:'Refusé · invalid',publication_id:client.id,origin:'system',conflict:false};const page=load('app/(cockpit)/publications/calendar/page.tsx',{'next/link':{default:({href,children,...props})=>React.createElement('a',{href,...props},children)},'@/lib/require-admin':{requireAdmin:async()=>({})},'@/lib/clients/data':{listClients:async()=>[]},'@/lib/projects/data':{listProjects:async()=>[]},'@/components/publications/publications-board':{PublicationsNav:()=>null},'@/lib/publications/planning':{getCalendar:async()=>[row,{...row,key:'free',status:'free',publication_id:null,origin:null}]},'@/lib/publications/calendar':engine,'@/lib/publications/types':types,'@/lib/publications/editor':editor,'@/components/ui/primitives':{PageHeading:({title})=>React.createElement('h1',{},title),Panel:({children})=>React.createElement('section',{},children),Badge:({children})=>React.createElement('span',{},children)}});const html=renderToStaticMarkup(await page.default({searchParams:Promise.resolve({date:'2026-10-12'})}));assert.match(html,/Slot libre/);assert.match(html,/Refusé/);assert.match(html,/Europe\/Paris/);assert.match(html,/Révision 1/);assert.match(html,/system/);assert.doesNotMatch(html,/Publier maintenant/);});
test('Lot 3 contains no external calls, workers or safety-setting mutations',()=>{for(const path of ['lib/publications/calendar.ts','lib/publications/planning.ts','lib/publications/agent-planning-context.ts','app/(cockpit)/publications/calendar/actions.ts'])assert.doesNotMatch(readFileSync(path,'utf8'),/fetch\(|openai|googleapis|graph\.facebook|setInterval|cron\.schedule|\.from\("publication_settings"\)\.(insert|update)/i);const sql=readFileSync('supabase/migrations/20261005205057_publications_editorial_calendar.sql','utf8');assert.doesNotMatch(sql,/update public\.publication_settings|insert into public\.publication_jobs|cron\.schedule/i);});
function agentContext({agent={id:client.id,agent_scope:'project',scope_review_required:false,enabled:true,status:'Actif'},assignment=true,admin=true}={}){
 const calls=[];const guard=async()=>{if(!admin)throw Error('denied');return {userId:'user_admin'};};
 const scope=load('lib/agents/scope.ts',{'@/lib/require-admin':{requireAdmin:guard}});
 const records={agents:[agent],projects:[project],clients:[{...client,name:'Client'}],agent_client_assignments:[{agent_id:agent.id,client_id:client.id,enabled:true}],agent_project_assignments:[{agent_id:agent.id,client_id:client.id,project_id:project.id,enabled:assignment}],publication_client_settings:[{client_id:client.id,editorial_brief:'Rules'}],publication_assets:[{id:'photo',client_id:client.id,rights_confirmed:true,provenance:'Owned',mime_type:'image/png',storage_path:'private-path'},{id:'foreign',client_id:'other',rights_confirmed:true}],publication_revisions:[{id:'rev',client_id:client.id,project_id:project.id},{id:'foreign-rev',client_id:client.id,project_id:'other'}],publication_variants:[{id:'variant',revision_id:'rev',client_id:client.id,text_content:'History'},{id:'other-variant',revision_id:'foreign-rev',client_id:client.id}],publication_reviews:[{id:'review',revision_id:'rev',client_id:client.id},{id:'other-review',revision_id:'foreign-rev',client_id:client.id}]};
 const db={from:table=>{calls.push(table);let rows=records[table]??[];const q={select:()=>q,eq:(k,v)=>{rows=rows.filter(r=>r[k]===v);return q;},order:()=>q,maybeSingle:async()=>({data:rows[0]??null,error:null}),single:async()=>({data:rows[0]??null,error:null}),range:async(a,b)=>({data:rows.slice(a,b+1),error:null})};return q;}};
 const p={getProjectCadence:async()=>cadence,projectPlanningJobs:async()=>[],planningRows:async(query)=>{const {data}=await query().range(0,99);return data;}};
 const model=load('lib/publications/agent-planning-context.ts',{'@/lib/require-admin':{requireAdmin:guard},'@/lib/supabase/server':{getSupabaseServerClient:()=>db},'@/lib/agents/scope':scope,'./validation':validation,'./planning':p,'./data':{listPublications:async()=>[]},'./calendar':engine});return {model,calls};
}
test('future agent context requires confirmed project scope and both active assignments',async()=>{
 for(const options of [{admin:false},{agent:{id:client.id,agent_scope:'client',scope_review_required:false,enabled:true}},{agent:{id:client.id,agent_scope:'project',scope_review_required:true,enabled:true}},{agent:{id:client.id,agent_scope:'project',scope_review_required:false,enabled:false}},{assignment:false}]){const {model,calls}=agentContext(options);await assert.rejects(()=>model.buildPublicationsAgentContext(client.id,project.id,period.start_week));assert.equal(calls.includes('publication_assets'),false);}
 const {model}=agentContext();const context=await model.buildPublicationsAgentContext(client.id,project.id,period.start_week);assert.equal(context.slots_to_fill.length,8);assert.equal(context.photos.length,1);assert.equal(context.photos[0].storage_path,undefined);assert.equal(context.variants.length,1);assert.equal(context.reviews.length,1);assert.equal(context.manual_approval_required,true);assert.equal(context.execution_enabled,false);
});
