/* eslint-disable @next/next/no-img-element -- Private signed URLs are short-lived and must not be cached by an image proxy. */
import Link from "next/link";
import {notFound} from "next/navigation";
import {requireAdmin} from "@/lib/require-admin";
import {getWorkspace} from "@/lib/publications/workspace";
import {listProjects} from "@/lib/projects/data";
import {listClients} from "@/lib/clients/data";
import {platformLabels} from "@/lib/publications/editor";
import {PublicationReviewForm,PublicationUploadForm} from "@/components/publications/workflow-forms";
import {AgentPrepareForm} from "@/components/publications/agent-forms";
import {PageHeading,Panel,Badge} from "@/components/ui/primitives";
import {formatDate} from "@/lib/format-date";
import {publicationActorLabel} from "@/lib/publications/actor-label";
const labels={draft:"Brouillon",pending_review:"À valider",approved:"Approuvée",rejected:"Refusée"};
const eventLabels:Record<string,string>={"publication.placeholder_created":"Brouillon vide créé par le système","publication.created":"Publication créée","publication.revised":"Nouvelle révision","publication.draft_saved":"Brouillon enregistré","publication.project_changed":"Projet modifié","publication.variant_saved":"Variante enregistrée","publication.media_uploaded":"Image privée ajoutée","publication.media_attached":"Image associée à la révision","publication.media_detached":"Image retirée de la révision","publication.submitted":"Révision soumise à validation","publication.reviewed":"Décision de validation enregistrée","publication.preparation_started":"Préparation manuelle démarrée","publication.media_catalog_read":"Catalogue de photos lu","publication.media_reserved":"Photo réservée","publication.ai_prepared":"Préparation IA soumise à validation","publication.preparation_failed":"Préparation interrompue ou échouée"};
export default async function PublicationDetailPage({params}:{params:Promise<{id:string}>}){
 await requireAdmin();const {id}=await params;const w=await getWorkspace(id);if(!w)notFound();const [projects,clients]=await Promise.all([listProjects(),listClients()]);const p=w.publication,revision=w.revisions.find(r=>r.id===p.current_revision_id),variants=w.variants.filter(v=>v.revision_id===p.current_revision_id);const section="mt-6 space-y-4 p-6";
 return <><PageHeading title={p.subject} eyebrow={`Publication · ${p.creation_origin??"manual"}`} description={`Révision ${revision?.revision_number??"—"} · Dernière modification ${formatDate(p.updated_at)}`}/><div className="flex flex-wrap items-center gap-4"><Badge>{labels[p.status]}</Badge><Link href="/publications" className="text-sm text-accent">← Publications</Link><Link href={`/publications/${id}/edit`} className="text-sm text-accent">Créer une nouvelle révision</Link></div>
 <Panel className={section}><h2 className="font-semibold">Client et projet</h2><p>{clients.find(c=>c.id===p.client_id)?.name??"Client indisponible"} · {projects.find(r=>r.id===p.project_id)?.name??"Historique sans projet"}</p><p className="text-sm text-muted">Date cible : {p.target_date?formatDate(p.target_date):"Non définie"} · Semaine du {formatDate(p.editorial_week)} · Créneau {p.slot}</p></Panel>
 <Panel className={section}><h2 className="font-semibold">Contenu source</h2><p className="whitespace-pre-wrap">{revision?.angle??"Angle historique non renseigné"}</p><p className="whitespace-pre-wrap text-sm">{revision?.source_content??"Source historique non renseignée"}</p></Panel>
 <Panel className={section}><h2 className="font-semibold">Variantes</h2>{variants.map(v=><article key={v.id}><h3>{platformLabels[v.platform]}</h3><p className="whitespace-pre-wrap text-sm">{v.text_content}</p></article>)}</Panel>
 <Panel className={section}><h2 className="font-semibold">Médias privés</h2><p className="text-sm text-muted">Aperçus temporaires, valables deux minutes. Rechargez la fiche pour les renouveler. Les images historiques restent conservées.</p><div className="grid gap-4 sm:grid-cols-3">{w.assets.map((a,index)=><figure key={a.id}>{a.preview?<img src={a.preview} alt={`Image ${index+1}`} className="max-h-60 w-full rounded-lg object-contain"/>:<p>Aperçu indisponible</p>}<figcaption className="mt-2 text-xs text-muted">Image {index+1} · {a.provenance}</figcaption></figure>)}</div>{p.current_revision_id&&<PublicationUploadForm id={id} revision={p.current_revision_id}/>}</Panel>
 <Panel className={section}><h2 className="font-semibold">Aperçus par plateforme</h2><div className="grid gap-5 lg:grid-cols-3">{variants.map(v=>{const m=v.metadata as {title?:string;cta?:string};return <article className="rounded-xl border border-border p-4" key={v.id}><h3 className="font-semibold">{platformLabels[v.platform]}</h3>{m.title&&<h4 className="mt-4 font-semibold">{m.title}</h4>}{w.links.filter(l=>l.variant_id===v.id).sort((a,b)=>a.sort_order-b.sort_order).map(l=>{const a=w.assets.find(a=>a.id===l.asset_id);return a?.preview?<img key={l.asset_id} src={a.preview} alt="Image associée" className="mt-4 max-h-64 w-full rounded-lg object-contain"/>:<p key={l.asset_id}>Image non disponible</p>;})}<p className="mt-4 whitespace-pre-wrap text-sm">{v.text_content}</p>{m.cta&&<p className="mt-4 rounded-lg border border-border p-2 text-sm">{m.cta}</p>}</article>;})}</div></Panel>
 <Panel className={section}><h2 className="font-semibold">Validation de la révision actuelle</h2>{p.current_revision_id&&<PublicationReviewForm id={id} revision={p.current_revision_id} status={p.status}/>} {w.reviews.filter(r=>r.revision_id===p.current_revision_id).map(r=><p className="text-sm" key={r.id}>{r.decision==="approved"?"Approuvé":"Refusé"} par {publicationActorLabel(r.actor_id)} le {formatDate(r.created_at)} · Révision {revision?.revision_number}{r.reason&&` · Motif : ${r.reason}`}</p>)}{p.status==='rejected'&&p.project_id&&<AgentPrepareForm projectId={p.project_id} publicationId={id} regenerate/>}</Panel>
 <Panel className={section}><h2 className="font-semibold">Historique des révisions</h2>{w.revisions.map(r=><details key={r.id} className="rounded-lg border border-border p-4"><summary>Version {r.revision_number} · {publicationActorLabel(r.actor_id)} · {formatDate(r.created_at)} {r.id===p.current_revision_id?"· Actuelle":"· Historique"}</summary><p className="mt-3 text-sm">Projet : {projects.find(p=>p.id===r.project_id)?.name??"Sans projet"}</p><p>{r.internal_title}</p><p className="whitespace-pre-wrap text-sm">{r.angle}</p><p className="whitespace-pre-wrap text-sm">{r.source_content}</p>{w.variants.filter(v=>v.revision_id===r.id).map(v=><p key={v.id} className="mt-4 whitespace-pre-wrap text-sm">{platformLabels[v.platform]} : {v.text_content}</p>)}{w.reviews.filter(v=>r.id!==p.current_revision_id&&v.revision_id===r.id).map(v=><p key={v.id} className="mt-2 text-xs text-muted">Validation historique : {v.decision} par {publicationActorLabel(v.actor_id)} · {formatDate(v.created_at)} · {v.reason}</p>)}</details>)}</Panel>
 <Panel className={section}><h2 className="font-semibold">Journal non supprimable</h2><ol className="space-y-3">{w.events.map(e=><li key={e.id} className="border-t border-border pt-3 text-sm"><p>{eventLabels[e.action]??"Événement interne"}</p><p className="text-xs text-muted">{formatDate(e.created_at)} · {publicationActorLabel(e.actor_id, e.actor_type)}</p></li>)}</ol></Panel>
 </>;
}
