"use client";
import {useActionState,useState} from "react";
import {savePublicationAction} from "@/app/(cockpit)/publications/actions";
import {allowedPlatforms,platformLabels} from "@/lib/publications/editor";
import type {Publication,PublicationRevision,PublicationVariant,PublicationAsset,PublicationVariantAsset} from "@/lib/publications/types";
const input="mt-2 w-full rounded-lg border border-border bg-background p-3 text-sm";
export function ManualPublicationForm({clients,projects,publication,revision,variants=[],assets=[],links=[]}:{clients:{id:string;name:string}[];projects:{id:string;client_id:string;name:string;type:string|null}[];publication?:Publication;revision?:PublicationRevision;variants?:PublicationVariant[];assets?:PublicationAsset[];links?:PublicationVariantAsset[]}){
 const [state,action,pending]=useActionState(savePublicationAction,{});const [client,setClient]=useState(publication?.client_id??"");const [project,setProject]=useState(publication?.project_id??"");const selected=projects.find(p=>p.id===project);const platforms=allowedPlatforms(selected?.type??null);
 return <form action={action} className="space-y-6">
 {publication&&<><input type="hidden" name="publication_id" value={publication.id}/><input type="hidden" name="revision_id" value={publication.current_revision_id??""}/><input type="hidden" name="client_id" value={client}/></>}
 <div className="grid gap-5 md:grid-cols-2"><label>Client<select className={input} name={publication?undefined:"client_id"} required value={client} disabled={Boolean(publication)} onChange={e=>{setClient(e.target.value);setProject("");}}><option value="">Choisir un client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
 <label>Projet<select className={input} name="project_id" required value={project} onChange={e=>setProject(e.target.value)}><option value="">Choisir un projet</option>{projects.filter(p=>p.client_id===client&&allowedPlatforms(p.type).length).map(p=><option key={p.id} value={p.id}>{p.name} · {p.type}</option>)}</select><span className="text-xs text-muted">Créez d’abord un projet Réseaux sociaux ou Google Business Profile pour ce client.</span></label></div>
 <label className="block">Titre interne<input className={input} name="title" required maxLength={300} defaultValue={revision?.internal_title??publication?.subject??""}/></label>
 <label className="block">Sujet / angle<textarea className={input} name="angle" required maxLength={3000} defaultValue={revision?.angle??publication?.subject??""}/></label>
 <label className="block">Contenu source<textarea className={input} name="source" rows={6} required maxLength={20000} defaultValue={revision?.source_content??variants[0]?.text_content??""}/></label>
 <div className="grid gap-5 md:grid-cols-3"><label>Date cible (facultative)<input className={input} name="target_date" type="date" defaultValue={revision?.target_date??publication?.target_date??""}/></label>{!publication&&<><label>Semaine éditoriale (lundi)<input className={input} type="date" name="week"/><span className="text-xs text-muted">Sans choix : semaine de la date cible, ou semaine actuelle.</span></label><label>Créneau<select className={input} name="slot"><option value="">Premier disponible</option><option value="1">1</option><option value="2">2</option></select></label></>}</div>
 <fieldset className="space-y-5"><legend className="mb-4 font-semibold">Variantes manuelles</legend>{!platforms.length&&<p className="text-sm text-muted">Choisissez un projet pour afficher ses plateformes.</p>}{platforms.map(platform=>{const v=variants.find(v=>v.platform===platform);const metadata=v?.metadata as {title?:string;cta?:string}|undefined;return <div key={platform} className="rounded-xl border border-border p-5"><label className="font-semibold"><input type="checkbox" name={platform+"_enabled"} defaultChecked={Boolean(v)||!publication?.current_revision_id}/> {platformLabels[platform]}</label><label className="mt-3 block text-sm">Texte<textarea className={input} name={platform+"_text"} rows={5} maxLength={10000} defaultValue={v?.text_content??""}/></label><div className="grid gap-4 md:grid-cols-2"><label>Titre facultatif<input className={input} name={platform+"_title"} maxLength={500} defaultValue={metadata?.title??""}/></label><label>CTA facultatif<input className={input} name={platform+"_cta"} maxLength={500} defaultValue={metadata?.cta??""}/></label></div>{assets.length>0&&<fieldset className="mt-4"><legend className="text-sm">Images associées (10 maximum)</legend>{assets.map((a,index)=><label className="mt-2 block text-sm" key={a.id}><input type="checkbox" name={platform+"_assets"} value={a.id} defaultChecked={links.some(l=>l.variant_id===v?.id&&l.asset_id===a.id)}/> Image {index+1} · {a.provenance}</label>)}</fieldset>}</div>;})}</fieldset>
 <p className="text-sm text-muted">L’enregistrement crée une révision en brouillon. Toute validation précédente devient historique. Retirer ou remplacer une image se fait en changeant sa sélection dans la nouvelle révision ; l’image historique reste conservée.</p>
 {state.message&&<p role="alert" className="text-sm text-red-400">{state.message}</p>}<button disabled={pending||!platforms.length} className="rounded-lg bg-accent px-5 py-3 text-sm font-semibold text-background disabled:opacity-50">{pending?"Enregistrement…":"Enregistrer le brouillon"}</button>
 </form>;
}
