"use client";
import {useActionState} from "react";
import {reviewPublicationAction,uploadPublicationImageAction} from "@/app/(cockpit)/publications/actions";
export function PublicationReviewForm({id,revision,status}:{id:string;revision:string;status:string}){
 const [state,action,pending]=useActionState(reviewPublicationAction,{});
 return <form action={action} className="mt-4 space-y-3"><input type="hidden" name="publication_id" value={id}/><input type="hidden" name="revision_id" value={revision}/>{status==="draft"?<button disabled={pending} name="decision" value="submit" className="rounded-lg bg-accent px-4 py-2 text-background">Soumettre à validation</button>:status==="pending_review"?<><label className="block">Motif du refus (obligatoire pour refuser)<textarea name="reason" maxLength={3000} className="mt-2 w-full rounded-lg border border-border bg-background p-3"/></label><div className="flex gap-3"><button disabled={pending} name="decision" value="approved" className="rounded-lg bg-accent px-4 py-2 text-background">Approuver cette révision</button><button disabled={pending} name="decision" value="rejected" className="rounded-lg border border-border px-4 py-2">Refuser cette révision</button></div></>:<p className="text-sm text-muted">Créez une nouvelle révision pour modifier le contenu ou demander une nouvelle validation.</p>}{state.message&&<p role="status">{state.message}</p>}</form>;
}
export function PublicationUploadForm({id,revision}:{id:string;revision:string}){
 const [state,action,pending]=useActionState(uploadPublicationImageAction,{});
 return <form action={action} className="mt-4 space-y-3"><input type="hidden" name="publication_id" value={id}/><input type="hidden" name="revision_id" value={revision}/><label className="block">Image privée (768 Ko maximum)<input className="mt-2 block w-full" name="image" type="file" accept="image/jpeg,image/png,image/webp" required/></label><label className="block">Provenance<input name="provenance" required maxLength={2000} className="mt-2 w-full rounded-lg border border-border bg-background p-3"/></label><label className="block"><input type="checkbox" name="rights" required/> Je confirme disposer des droits d’utilisation.</label><button disabled={pending} className="rounded-lg border border-border px-4 py-2">{pending?"Upload…":"Ajouter l’image"}</button>{state.message&&<p role="status">{state.message}</p>}</form>;
}
