import Link from "next/link";
import {requireAdmin} from "@/lib/require-admin";
import {listClients} from "@/lib/clients/data";
import {listProjects} from "@/lib/projects/data";
import {getCalendar} from "@/lib/publications/planning";
import {calendarPeriod,calendarStatusLabels,parisToday,validDate} from "@/lib/publications/calendar";
import {publicationPlatforms} from "@/lib/publications/types";
import {platformLabels} from "@/lib/publications/editor";
import {PageHeading,Panel,Badge} from "@/components/ui/primitives";
import {PublicationsNav} from "@/components/publications/publications-board";
export default async function CalendarPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 await requireAdmin();const search=await searchParams;const field=(key:string)=>typeof search[key]==="string"?search[key] as string:"";const mode=field("mode")==="month"?"month":"week",date=validDate(field("date"))?field("date"):parisToday(),period=calendarPeriod(date,mode);
 const filter={...period,client:field("client"),project:field("project"),platform:field("platform"),status:field("status")};
 const [clients,projects]=await Promise.all([listClients(),listProjects()]);let entries:Awaited<ReturnType<typeof getCalendar>>=[];let error="";try{entries=await getCalendar(filter);}catch{error="Calendrier indisponible. Vérifiez l’accès au stockage et l’installation du calendrier.";}
 const input="w-full rounded-lg border border-border bg-background p-3";
 return <><PageHeading title="Calendrier éditorial" eyebrow="Planification" description="Créneaux et validation de tous les clients. Aucun contenu n’est publié." action={<PublicationsNav current="calendar"/>}/>
 <Panel className="p-5"><form method="get" className="grid gap-3 md:grid-cols-3"><label>Vue<select className={input} name="mode" defaultValue={mode}><option value="week">Semaine</option><option value="month">Mois</option></select></label><label>Date de référence<input className={input} type="date" name="date" defaultValue={date}/></label><label>Client<select name="client" className={input} defaultValue={filter.client}><option value="">Tous</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Projet<select name="project" className={input} defaultValue={filter.project}><option value="">Tous</option>{projects.filter(p=>!filter.client||p.client_id===filter.client).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Plateforme<select name="platform" className={input} defaultValue={filter.platform}><option value="">Toutes</option>{publicationPlatforms.map(p=><option key={p} value={p}>{platformLabels[p]}</option>)}</select></label><label>Statut<select name="status" className={input} defaultValue={filter.status}><option value="">Tous</option>{Object.entries(calendarStatusLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button className="rounded-lg border border-border p-3">Filtrer</button><Link href="/publications/calendar" className="self-center text-accent">Réinitialiser</Link></form></Panel>
 <Panel className="mt-6 p-5"><p className="text-sm text-muted">{period.from} → {period.to} · {entries.length} entrée(s). Les slots libres sont réservés depuis la fiche projet. Les heures sont affichées dans leur fuseau.</p>{error?<p role="alert" className="mt-4">{error}</p>:!entries.length?<p className="mt-4">Aucun créneau pour ces critères. Configurez la planification sur un projet Réseaux sociaux ou Google Business Profile.</p>:<div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Date / heure","Client / projet","Sujet","Plateformes","Statut","Révision / validation","Origine"].map(t=><th key={t} className="border-b border-border p-3">{t}</th>)}</tr></thead><tbody>{entries.map(e=><tr key={e.key}><td className="border-b border-border p-3">{e.date} · {e.time??"Horaire à définir"}<p className="text-xs text-muted">{e.timezone}</p></td><td className="border-b border-border p-3">{e.client_name}<Link href={e.project_id?`/projects/${e.project_id}`:"/projects"} className="block text-accent">{e.project_name}</Link></td><td className="border-b border-border p-3">{e.publication_id?<Link className="text-accent" href={`/publications/${e.publication_id}`}>{e.subject}</Link>:e.subject}{e.conflict&&<p className="text-xs">Conflit : revue manuelle requise</p>}</td><td className="border-b border-border p-3">{e.platforms.map(p=>platformLabels[p]).join(", ")}</td><td className="border-b border-border p-3"><Badge>{calendarStatusLabels[e.status]}</Badge></td><td className="border-b border-border p-3">Révision {e.revision??"—"}<p>{e.validation}</p></td><td className="border-b border-border p-3">{e.origin??"Créneau libre"}</td></tr>)}</tbody></table></div>}</Panel></>;
}
